export const petitionTargets = [
    'Ministry of Agriculture',
    'Ministry of Civil Aviation and Tourism',
    'Ministry of Cultural Affairs',
    "Prime Minister's Office",
    'Armed Forces Division',
    'Cabinet Division',
    'Ministry of Chittagong Hill Tracts Affairs',
    'Ministry of Primary and Mass Education',
    'Ministry of Commerce',
    'Ministry of Road Transport and Bridges',
    'Ministry of Defence',
    'Ministry of Food',
    'Ministry of Education',
    'Ministry of Power, Energy and Mineral Resources',
    'Ministry of Environment and Forest',
    'Ministry of Public Administration',
    'Ministry of Fisheries and Livestock',
    'Ministry of Finance',
    'Ministry of Foreign Affairs',
    'Ministry of Health and Family Welfare',
    'Ministry of Home Affairs',
    'Ministry of Housing and Public Works',
    'Ministry of Industries',
    'Ministry of Information',
    'Ministry of Textiles and Jute',
    'Ministry of Labour & Employment',
    'Ministry of Law, Justice and Parliamentary Affairs',
    'Ministry of Land',
    'Ministry of Local Government, Rural Development and Co-operatives',
    'Ministry of Planning',
    'Ministry of Religious Affairs',
    'Ministry of Shipping',
    'Ministry of Social Welfare',
    'Ministry of Women and Children Affairs',
    'Ministry of Water Resources',
    'Ministry of Youth and Sports',
    'Ministry of Liberation War Affairs',
    "Ministry of Expatriates' Welfare and Overseas Employment",
    'Ministry of Railways',
    'Ministry of Science and Technology',
    'Ministry of Disaster Management and Relief',
];

export const petitionLocations = [
    'Dhaka',
    'Chittagong',
    'Rajshahi',
    'Khulna',
    'Barisal',
    'Sylhet',
    'Rangpur',
    'Mymensingh',
    'Gazipur',
    'Narayanganj',
    'Comilla',
    'Savar',
    'Tangail',
    'Jessore',
    "Cox's Bazar",
    'Narsingdi',
    'Bogra',
    'Dinajpur',
    'Madaripur',
    'Kushtia',
    'Faridpur',
    'Feni',
    'Pabna',
    'Patuakhali',
    'Rangamati',
    'Manikganj',
    'Natore',
    'Jhenaidah',
    'Pirojpur',
    'Lalmonirhat',
    'Habiganj',
    'Sunamganj',
    'Sirajganj',
    'Lakshmipur',
    'Bagerhat',
    'Brahmanbaria',
    'Jhalokathi',
    'Jamalpur',
    'Shariatpur',
    'Kurigram',
    'Gaibandha',
    'Meherpur',
    'Narail',
    'Magura',
    'Bandarban',
    'Khagrachhari',
    'Thakurgaon',
    'Chuadanga',
    'Nilphamari',
    'Munshiganj',
    'Noakhali',
    'Chapainawabganj',
    'Moulvibazar',
    'Gopalganj',
    'Sherpur',
    'Kishoreganj',
    'Maulvibazar',
    'Netrokona',
    'Panchagarh',
    'Joypurhat',
    'Bhola',
    'Naogaon',
    'Chandpur',
    'Satkhira',
    'Barguna',
    'Bhola',
    'Patuakhali',
    'Chuadanga',
    'Bogra',
    'Moulvibazar',
    'Tangail',
    'Jashore',
    'Madaripur',
];
