// Generated by Wrangler on Tue Nov 05 2024 15:28:38 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	RENDERING_SYMMETRIC_KEY: string;
}
