export const petitionTopics = [
    'Human Rights',
    'Social Justice',
    'Education Reform',
    'Healthcare Reform',
    'Government Transparency',
    'Environmental Protection',
    'Animal Rights',
    'Worker Rights',
    'Gender Equality',
    'Criminal Justice Reform',
    'Gun Control',
    'Immigration Reform',
    'Climate Change Action',
    'Voting Rights',
    'Consumer Rights',
    'Privacy Rights',
    'Affordable Housing',
    'Mental Health Awareness',
    'Disability Rights',
];

export const ministries = [
    'Ministry of Agriculture',
    'Ministry of Commerce',
    'Ministry of Communication',
    'Ministry of Defence',
    'Ministry of Education',
    'Ministry of Environment, Forest and Climate Change',
    'Ministry of Finance',
    'Ministry of Foreign Affairs',
    'Ministry of Health and Family Welfare',
    'Ministry of Home Affairs',
    'Ministry of Information',
    'Ministry of Labour and Employment',
    'Ministry of Land',
    'Ministry of Local Government, Rural Development and Co-operatives',
    'Ministry of Public Administration',
    'Ministry of Railways',
    'Ministry of Social Welfare',
    'Ministry of Sports and Youth Affairs',
    'Ministry of Textiles and Jute',
    'Ministry of Water Resources',
    'Ministry of Planning',
    'Ministry of Industries',
    'Ministry of Religious Affairs',
    'Ministry of Shipping',
    'Ministry of Civil Aviation and Tourism',
    'Ministry of Post and Telecommunications',
    'Ministry of Law, Justice and Parliamentary Affairs',
    'Ministry of Information and Broadcasting',
    'Ministry of Science and Technology',
    'Ministry of Energy and Mineral Resources',
    'Ministry of Youth and Sports',
    'Ministry of Social Welfare',
    'Ministry of Health and Family Welfare',
];
