const petitions = [
    {
        id: 1,
        title: 'Reform Bangladesh Army and Police',
        description:
            'We are writing to draw your urgent attention to the escalating human rights crisis, oppression, and mass killing  in Bangladesh, which has particularly endangered the lives of thousands of general students along with the general people of Bangladesh. Recent events have demonstrated an alarming trend of excessive deployment of force by the ruling government of Bangladesh and consequential human rights violations by the government law enforcement agencies- 1) Bangladesh Police, 2) Detective Branch (DB), 3) Rapid Action Battalion (RAB), and 4) Border Guard Bangladesh (BGB), along with the Bangladesh Student League, a student organization aligned with the current government which is considered as a terrorist organization by the majority of the people of Bangladesh. According to various reports, at least 180 (REF: CBS NEWS) people, the majority of them students, have been killed, and countless others injured, in the last three days of deadly oppression (July 17-19, 2024). The death tolls can be significantly higher due to - 1) denial of admissions in hospitals of critically injured protestors, 2) stealing death registers from the major hospitals, and 3) concealing of dead-bodies while a total communication black-out was in effect. Initially, Bangladesh Army had played a quiet role, until they were called upon by the failed government for implementing a strict curfew including an order of shoot-on-sight after 3 days of illegal killing of unarmed civilian protestors. Eventually, Bangladesh Army joined the government-led genocide and deployed military equipment some of which were UN marked. Many videos of shooting and bombing from helicopters targeting civilians and buildings located at densely populated residential areas got viral. Many reports and videos show heavy usage of AK-47 and Chinese Type 56 SKS Rifles for targeted shooting on unarmed civilians. Former Bangladeshi officers who served in UN Peace Mission, were spotted targeting and shooting unarmed civilians using AK-47. Use of such deadly assault weapons to disarray a civilian crowd is a clear violation of the Geneva Conventions. A Deutsche Welle investigation has revealed that vehicles with UN markings have been deployed in the crackdown to quench the protests of unarmed students and general people. This letter urges the United Nations to take immediate action to address these illegal killings and consider disengaging the involved Bangladeshi forces from UN peacekeeping missions.',
        goal: 100,
        current: 50,
    },
];
